#pragma once

#include "vshadersystem/result.hpp"
#include "vshadersystem/types.hpp"

#include <optional>
#include <string>
#include <vector>

namespace vshadersystem
{
    struct Define
    {
        std::string name;
        std::string value;
    };

    struct CompileOptions
    {
        ShaderStage stage = ShaderStage::eUnknown;

        // Entry point function name.
        // - For GLSL, if not "main", vshadersystem will generate a wrapper main() calling entryPoint.
        std::string entryPoint = "main";

        ShaderLanguage     language           = ShaderLanguage::eAuto;
        MaterialAccessMode materialAccessMode = MaterialAccessMode::eBDA;

        // Target SPIR-V version. glslang uses Vulkan/OpenGL envs; we expose a minimal target here.
        int spirvVersion = 0; // 0 = default for environment
        // Use the WebGPU-oriented compile profile. This currently aligns the
        // Vulkan client environment with Tint SPIR-V reader expectations.
        bool webgpuProfile = false;

        bool optimize       = false;
        bool debugInfo      = false;
        bool stripDebugInfo = false;

        std::vector<Define>      defines;
        std::vector<std::string> includeDirs;

        // --------------------------------------------------------------------
        // MaterialAccessInjection (tool-layer contract)
        // --------------------------------------------------------------------
        //
        // vshadersystem is a tool-layer shader compiler. To keep it engine-
        // agnostic, engine-specific bindings (set/binding, GPUScene layouts,
        // draw-record formats) are provided via an optional injection bundle.
        //
        // If present, vshadersystem will inject:
        //   1) injection.preamble (after #version/#extension directives)
        //   2) a small wrapper API and convenience macros for material access
        //
        // The underlying material load function is still generated by the
        // backend injector (vshader_LoadMaterial(...)), and the wrapper simply
        // supplies the address/index expression.
        // --------------------------------------------------------------------

        struct MaterialAccessInjection
        {
            // Injected after #version/#extension directives, before any shader code.
            std::string preamble;

            // Expression returning uint64_t material address (for eBDA).
            // Example: "g_Draws.draws[gl_DrawID].materialAddress".
            std::string materialAddressExpr;

            // Expression returning material index (for eSSBO).
            // Example: "g_Draws.draws[gl_DrawID].materialIndex".
            std::string materialIndexExpr;

            // Optional bindless texture array identifier used by injected macros.
            // Example: "textures" for "uniform sampler2D textures[];".
            std::string bindlessTextureArrayName;

            // Macro/function prefix to avoid collisions. Default: "VSH_".
            std::string macroPrefix = "VSH_";
        };

        std::optional<MaterialAccessInjection> materialInjection;

        // --------------------------------------------------------------------
        // Debug / diagnostics
        // --------------------------------------------------------------------
        // If enabled, when compilation fails, vshadersystem appends a source
        // context dump (error line + surrounding lines) to the returned error
        // message. This is extremely helpful for generated/injected shaders.
        bool dumpSourceOnError = true;

        // Number of context lines printed above and below an error line.
        // Total shown will be (2 * dumpContextLines + 1).
        int dumpContextLines = 5;

        // If non-empty, emit the final, compiled source into this directory.
        // The file name is derived from virtualPath and stage.
        // Useful for offline reproduction with external tools.
        std::string emitIntermediateDir;

        // Emit intermediate source even if compilation succeeds.
        bool emitIntermediateAlways = false;

        // We can extend this with macro stripping, warnings as errors, etc.
    };

    struct SourceInput
    {
        std::string virtualPath; // used for includes and diagnostics
        std::string sourceText;
    };

    struct CompileOutput
    {
        std::vector<uint32_t>    spirv;
        std::string              infoLog;
        std::vector<std::string> dependencies;

        ShaderReflection reflection;
    };

    Result<CompileOutput> compile_glsl_to_spirv(const SourceInput& input, const CompileOptions& opt);
} // namespace vshadersystem
